2025-03-11 16:58:38,550 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for in-memory database (connection.py:318)
2025-03-11 16:58:38,550 - MainThread - sqlmesh.core.console - WARNING - Model '"DB_ADI_SQLMESH_DEV"."SQLMESH_EXAMPLE"."FULL_MODEL"' was not found at C:\SQLMESH_DEV\tests\test_full_model.yaml (console.py:1269)
2025-03-11 16:58:38,553 - MainThread - sqlmesh.core.console - WARNING - The snowflake engine is not recommended for storing SQLMesh state in production deployments. Please see https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#state-connection for a list of recommended engines and more information. (console.py:1269)
2025-03-11 16:58:38,558 - MainThread - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 16:58:38,559 - MainThread - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 16:58:38,559 - MainThread - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 16:58:42,888 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 16:58:46,047 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 16:58:46,227 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 16:58:46,410 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
2025-03-11 16:58:46,530 - MainThread - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
