2025-03-12 10:28:40,590 - MainThread - sqlmesh.core.console - WARNING - The snowflake engine is not recommended for storing SQLMesh state in production deployments. Please see https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#state-connection for a list of recommended engines and more information. (console.py:1269)
2025-03-12 10:28:40,611 - MainThread - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-12 10:28:40,611 - MainThread - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-12 10:28:40,612 - MainThread - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-12 10:28:44,701 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:28:48,288 - MainThread - sqlmesh.core.state_sync.db.interval - INFO - Compacting 0 intervals for 0 snapshots (interval.py:127)
2025-03-12 10:28:49,670 - MainThread - sqlmesh.core.state_sync.db.interval - INFO - Compacting 0 intervals for 0 snapshots (interval.py:127)
2025-03-12 10:28:50,110 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:28:55,309 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:28:56,382 - ThreadPoolExecutor-15_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-12 10:28:56,383 - ThreadPoolExecutor-15_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-12 10:28:56,383 - ThreadPoolExecutor-15_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-12 10:28:57,552 - ThreadPoolExecutor-15_1 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-12 10:28:57,553 - ThreadPoolExecutor-15_1 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-12 10:28:57,553 - ThreadPoolExecutor-15_1 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-12 10:28:59,103 - ThreadPoolExecutor-15_2 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-12 10:28:59,104 - ThreadPoolExecutor-15_2 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-12 10:28:59,104 - ThreadPoolExecutor-15_2 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-12 10:29:00,532 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:00,622 - ThreadPoolExecutor-15_2 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_STAGE": 4018518091> (evaluator.py:595)
2025-03-12 10:29:00,623 - ThreadPoolExecutor-15_1 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_STAGE": 2772891127> (evaluator.py:595)
2025-03-12 10:29:00,623 - ThreadPoolExecutor-15_2 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-12 10:29:00,623 - ThreadPoolExecutor-15_2 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-12 10:29:00,623 - ThreadPoolExecutor-15_2 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-12 10:29:00,660 - ThreadPoolExecutor-15_0 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_STAGE": 4240791175> (evaluator.py:595)
2025-03-12 10:29:01,812 - ThreadPoolExecutor-15_2 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-03-11 00:00:00, 2025-03-12 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__ORDER_STAGE__2493001244' (evaluator.py:649)
2025-03-12 10:29:01,812 - ThreadPoolExecutor-15_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_STAGE__2493001244" (base.py:2113)
2025-03-12 10:29:01,813 - ThreadPoolExecutor-15_1 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-12 10:29:01,813 - ThreadPoolExecutor-15_1 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-12 10:29:01,813 - ThreadPoolExecutor-15_1 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-12 10:29:03,405 - ThreadPoolExecutor-15_1 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-03-11 00:00:00, 2025-03-12 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__CUSTOMER_STAGE__3527124355' (evaluator.py:649)
2025-03-12 10:29:03,406 - ThreadPoolExecutor-15_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" (base.py:2113)
2025-03-12 10:29:03,406 - ThreadPoolExecutor-15_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-12 10:29:03,406 - ThreadPoolExecutor-15_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-12 10:29:03,406 - ThreadPoolExecutor-15_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-12 10:29:05,060 - ThreadPoolExecutor-15_0 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-03-11 00:00:00, 2025-03-12 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__PRODUCT_STAGE__8161499' (evaluator.py:649)
2025-03-12 10:29:05,061 - ThreadPoolExecutor-15_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_STAGE__8161499" (base.py:2113)
2025-03-12 10:29:05,656 - ThreadPoolExecutor-15_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_STAGE__2493001244" AS SELECT CAST("ORDERID" AS DECIMAL(38, 0)) AS "ORDERID", CAST("ORDERDATE" AS VARCHAR(16777216)) AS "ORDERDATE", CAST("SHIPDATE" AS VARCHAR(16777216)) AS "SHIPDATE", CAST("SHIPMODE" AS VARCHAR(16777216)) AS "SHIPMODE", CAST("CUSTOMERID" AS VARCHAR(16777216)) AS "CUSTOMERID", CAST("PRODUCTID" AS VARCHAR(16777216)) AS "PRODUCTID", CAST("ORDERCOSTPRICE" AS DECIMAL(38, 0)) AS "ORDERCOSTPRICE", CAST("ORDERSELLINGPRICE" AS DECIMAL(38, 0)) AS "ORDERSELLINGPRICE" FROM (SELECT "ORDERID" AS "ORDERID", "ORDERDATE" AS "ORDERDATE", "SHIPDATE" AS "SHIPDATE", "SHIPMODE" AS "SHIPMODE", "CUSTOMERID" AS "CUSTOMERID", "PRODUCTID" AS "PRODUCTID", "ORDERCOSTPRICE" AS "ORDERCOSTPRICE", "ORDERSELLINGPRICE" AS "ORDERSELLINGPRICE" FROM "DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDERS_T" AS "ORDERS_T") AS "_subquery" (base.py:2113)
2025-03-12 10:29:05,678 - ThreadPoolExecutor-15_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" AS SELECT CAST("CUSTOMERID" AS VARCHAR(16777216)) AS "CUSTOMERID", CAST("CUSTOMERNAME" AS VARCHAR(16777216)) AS "CUSTOMERNAME", CAST("SEGMENT" AS VARCHAR(16777216)) AS "SEGMENT", CAST("COUNTRY" AS VARCHAR(16777216)) AS "COUNTRY" FROM (SELECT "CUSTOMERID" AS "CUSTOMERID", "CUSTOMERNAME" AS "CUSTOMERNAME", "SEGMENT" AS "SEGMENT", "COUNTRY" AS "COUNTRY" FROM "DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMERS_T" AS "CUSTOMERS_T") AS "_subquery" (base.py:2113)
2025-03-12 10:29:05,746 - ThreadPoolExecutor-15_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_STAGE__8161499" AS SELECT CAST("CATEGORY" AS VARCHAR(16777216)) AS "CATEGORY", CAST("PRODUCTID" AS VARCHAR(16777216)) AS "PRODUCTID", CAST("PRODUCTNAME" AS VARCHAR(16777216)) AS "PRODUCTNAME", CAST("SUBCATEGORY" AS VARCHAR(16777216)) AS "SUBCATEGORY" FROM (SELECT "CATEGORY" AS "CATEGORY", "PRODUCTID" AS "PRODUCTID", "PRODUCTNAME" AS "PRODUCTNAME", "SUBCATEGORY" AS "SUBCATEGORY" FROM "DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCTS_T" AS "PRODUCTS_T") AS "_subquery" (base.py:2113)
2025-03-12 10:29:06,132 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:07,121 - ThreadPoolExecutor-15_2 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-03-11 00:00:00, 2025-03-12 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_STAGE": 4018518091> (facade.py:506)
2025-03-12 10:29:07,121 - ThreadPoolExecutor-15_1 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-03-11 00:00:00, 2025-03-12 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_STAGE": 2772891127> (facade.py:506)
2025-03-12 10:29:07,122 - ThreadPoolExecutor-15_2 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_STAGE": 4018518091> (interval.py:210)
2025-03-12 10:29:07,122 - ThreadPoolExecutor-15_1 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_STAGE": 2772891127> (interval.py:210)
2025-03-12 10:29:07,307 - ThreadPoolExecutor-15_0 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-03-11 00:00:00, 2025-03-12 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_STAGE": 4240791175> (facade.py:506)
2025-03-12 10:29:07,307 - ThreadPoolExecutor-15_0 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_STAGE": 4240791175> (interval.py:210)
2025-03-12 10:29:11,426 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:16,617 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:17,334 - ThreadPoolExecutor-15_2 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_PROFIT": 2121590543> (evaluator.py:595)
2025-03-12 10:29:17,451 - ThreadPoolExecutor-15_2 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-03-11 00:00:00, 2025-03-12 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__ORDER_PROFIT__417197957' (evaluator.py:649)
2025-03-12 10:29:17,452 - ThreadPoolExecutor-15_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" (base.py:2113)
2025-03-12 10:29:17,788 - ThreadPoolExecutor-15_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS SELECT CAST("ORDERID" AS DECIMAL(38, 0)) AS "ORDERID", CAST("ORDERDATE" AS VARCHAR(16777216)) AS "ORDERDATE", CAST("CUSTOMERID" AS VARCHAR(16777216)) AS "CUSTOMERID", CAST("PRODUCTID" AS VARCHAR(16777216)) AS "PRODUCTID", CAST("SHIPDATE" AS VARCHAR(16777216)) AS "SHIPDATE", CAST("SHIPMODE" AS VARCHAR(16777216)) AS "SHIPMODE", CAST("ORDERCOSTPRICE" AS DECIMAL(38, 0)) AS "ORDERCOSTPRICE", CAST("ORDERSELLINGPRICE" AS DECIMAL(38, 0)) AS "ORDERSELLINGPRICE", CAST("ORDERPROFIT" AS DECIMAL(38, 0)) AS "ORDERPROFIT", CAST("CUSTOMERNAME" AS VARCHAR(16777216)) AS "CUSTOMERNAME", CAST("SEGMENT" AS VARCHAR(16777216)) AS "SEGMENT", CAST("COUNTRY" AS VARCHAR(16777216)) AS "COUNTRY", CAST("CATEGORY" AS VARCHAR(16777216)) AS "CATEGORY", CAST("PRODUCTNAME" AS VARCHAR(16777216)) AS "PRODUCTNAME", CAST("SUBCATEGORY" AS VARCHAR(16777216)) AS "SUBCATEGORY" FROM (SELECT "O"."ORDERID" AS "ORDERID", "O"."ORDERDATE" AS "ORDERDATE", "O"."CUSTOMERID" AS "CUSTOMERID", "O"."PRODUCTID" AS "PRODUCTID", "O"."SHIPDATE" AS "SHIPDATE", "O"."SHIPMODE" AS "SHIPMODE", "O"."ORDERCOSTPRICE" AS "ORDERCOSTPRICE", "O"."ORDERSELLINGPRICE" AS "ORDERSELLINGPRICE", "O"."ORDERSELLINGPRICE" - "O"."ORDERCOSTPRICE" AS "ORDERPROFIT", "C"."CUSTOMERNAME" AS "CUSTOMERNAME", "C"."SEGMENT" AS "SEGMENT", "C"."COUNTRY" AS "COUNTRY", "P"."CATEGORY" AS "CATEGORY", "P"."PRODUCTNAME" AS "PRODUCTNAME", "P"."SUBCATEGORY" AS "SUBCATEGORY" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_STAGE__2493001244" AS "O" JOIN "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" AS "C" ON "C"."CUSTOMERID" = "O"."CUSTOMERID" JOIN "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_STAGE__8161499" AS "P" ON "O"."PRODUCTID" = "P"."PRODUCTID") AS "_subquery" (base.py:2113)
2025-03-12 10:29:20,175 - ThreadPoolExecutor-15_2 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-03-11 00:00:00, 2025-03-12 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_PROFIT": 2121590543> (facade.py:506)
2025-03-12 10:29:20,175 - ThreadPoolExecutor-15_2 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_PROFIT": 2121590543> (interval.py:210)
2025-03-12 10:29:21,891 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:27,130 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:29,206 - ThreadPoolExecutor-15_2 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_PROFIT": 1238932029> (evaluator.py:595)
2025-03-12 10:29:29,214 - ThreadPoolExecutor-15_2 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-03-11 00:00:00, 2025-03-12 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__PRODUCT_PROFIT__136943708' (evaluator.py:649)
2025-03-12 10:29:29,215 - ThreadPoolExecutor-15_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_PROFIT__136943708" (base.py:2113)
2025-03-12 10:29:29,217 - ThreadPoolExecutor-15_1 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_PROFIT": 2716878988> (evaluator.py:595)
2025-03-12 10:29:29,223 - ThreadPoolExecutor-15_1 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-03-11 00:00:00, 2025-03-12 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__CUSTOMER_PROFIT__4259417223' (evaluator.py:649)
2025-03-12 10:29:29,224 - ThreadPoolExecutor-15_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_PROFIT__4259417223" (base.py:2113)
2025-03-12 10:29:29,448 - ThreadPoolExecutor-15_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_PROFIT__4259417223" AS SELECT CAST("CUSTOMERID" AS VARCHAR(16777216)) AS "CUSTOMERID", CAST("SEGMENT" AS VARCHAR(16777216)) AS "SEGMENT", CAST("COUNTRY" AS VARCHAR(16777216)) AS "COUNTRY", CAST("PROFIT" AS DECIMAL(38, 0)) AS "PROFIT" FROM (SELECT "ORDER_PROFIT"."CUSTOMERID" AS "CUSTOMERID", "ORDER_PROFIT"."SEGMENT" AS "SEGMENT", "ORDER_PROFIT"."COUNTRY" AS "COUNTRY", SUM("ORDER_PROFIT"."ORDERPROFIT") AS "PROFIT" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS "ORDER_PROFIT" GROUP BY "ORDER_PROFIT"."CUSTOMERID", "ORDER_PROFIT"."SEGMENT", "ORDER_PROFIT"."COUNTRY") AS "_subquery" (base.py:2113)
2025-03-12 10:29:29,468 - ThreadPoolExecutor-15_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_PROFIT__136943708" AS SELECT CAST("PRODUCTID" AS VARCHAR(16777216)) AS "PRODUCTID", CAST("PRODUCTNAME" AS VARCHAR(16777216)) AS "PRODUCTNAME", CAST("CATEGORY" AS VARCHAR(16777216)) AS "CATEGORY", CAST("SUBCATEGORY" AS VARCHAR(16777216)) AS "SUBCATEGORY", CAST("PROFIT" AS DECIMAL(38, 0)) AS "PROFIT" FROM (SELECT "ORDER_PROFIT"."PRODUCTID" AS "PRODUCTID", "ORDER_PROFIT"."PRODUCTNAME" AS "PRODUCTNAME", "ORDER_PROFIT"."CATEGORY" AS "CATEGORY", "ORDER_PROFIT"."SUBCATEGORY" AS "SUBCATEGORY", SUM("ORDER_PROFIT"."ORDERPROFIT") AS "PROFIT" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS "ORDER_PROFIT" GROUP BY "ORDER_PROFIT"."PRODUCTID", "ORDER_PROFIT"."PRODUCTNAME", "ORDER_PROFIT"."CATEGORY", "ORDER_PROFIT"."SUBCATEGORY") AS "_subquery" (base.py:2113)
2025-03-12 10:29:31,512 - ThreadPoolExecutor-15_2 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-03-11 00:00:00, 2025-03-12 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_PROFIT": 1238932029> (facade.py:506)
2025-03-12 10:29:31,512 - ThreadPoolExecutor-15_2 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_PROFIT": 1238932029> (interval.py:210)
2025-03-12 10:29:31,530 - ThreadPoolExecutor-15_1 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-03-11 00:00:00, 2025-03-12 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_PROFIT": 2716878988> (facade.py:506)
2025-03-12 10:29:31,530 - ThreadPoolExecutor-15_1 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_PROFIT": 2716878988> (interval.py:210)
2025-03-12 10:29:32,397 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:37,583 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:39,998 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-12 10:29:40,809 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-12 10:29:41,036 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-12 10:29:41,253 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-12 10:29:41,627 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-12 10:29:42,153 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-12 10:29:42,787 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-12 10:29:42,984 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-12 10:29:43,244 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-12 10:29:43,546 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-12 10:29:43,781 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-12 10:29:44,249 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-12 10:29:44,820 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-12 10:29:45,413 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-12 10:29:45,948 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-12 10:29:46,179 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
2025-03-12 10:29:46,616 - MainThread - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
