2025-03-11 17:16:42,277 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for in-memory database (connection.py:318)
2025-03-11 17:16:42,277 - MainThread - sqlmesh.core.console - WARNING - Model '"DB_ADI_SQLMESH_DEV"."SQLMESH_EXAMPLE"."FULL_MODEL"' was not found at C:\SQLMESH_DEV\tests\test_full_model.yaml (console.py:1269)
2025-03-11 17:16:42,281 - MainThread - sqlmesh.core.console - WARNING - The snowflake engine is not recommended for storing SQLMesh state in production deployments. Please see https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#state-connection for a list of recommended engines and more information. (console.py:1269)
2025-03-11 17:16:42,286 - MainThread - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:16:42,286 - MainThread - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:16:42,286 - MainThread - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:16:47,043 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:16:52,171 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:16:57,341 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:02,826 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:05,327 - ThreadPoolExecutor-12_0 - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH (evaluator.py:323)
2025-03-11 17:17:05,329 - ThreadPoolExecutor-12_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:05,329 - ThreadPoolExecutor-12_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:05,329 - ThreadPoolExecutor-12_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:06,718 - ThreadPoolExecutor-12_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_DATABASE() (base.py:2113)
2025-03-11 17:17:07,289 - ThreadPoolExecutor-12_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_DATABASE() (base.py:2113)
2025-03-11 17:17:08,035 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:08,095 - ThreadPoolExecutor-12_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT DISTINCT "TABLE_CATALOG" AS "catalog", "TABLE_NAME" AS "name", "TABLE_SCHEMA" AS "schema_name", CASE WHEN "TABLE_TYPE" = 'BASE TABLE' AND "IS_DYNAMIC" = 'YES' THEN 'MANAGED_TABLE' WHEN "TABLE_TYPE" = 'BASE TABLE' THEN 'TABLE' WHEN "TABLE_TYPE" = 'TEMPORARY TABLE' THEN 'TABLE' WHEN "TABLE_TYPE" = 'LOCAL TEMPORARY' THEN 'TABLE' WHEN "TABLE_TYPE" = 'EXTERNAL TABLE' THEN 'TABLE' WHEN "TABLE_TYPE" = 'EVENT TABLE' THEN 'TABLE' WHEN "TABLE_TYPE" = 'VIEW' THEN 'VIEW' WHEN "TABLE_TYPE" = 'MATERIALIZED VIEW' THEN 'MATERIALIZED_VIEW' ELSE "TABLE_TYPE" END AS "type", "CLUSTERING_KEY" AS "clustering_key" FROM "DB_ADI_SQLMESH_DEV"."INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_SCHEMA" = 'sqlmesh__SQLMESH' AND "TABLE_NAME" IN ('SQLMESH__PRODUCT_STAGE__8161499', 'SQLMESH__CUSTOMER_STAGE__3527124355', 'SQLMESH__PRODUCT_PROFIT__136943708', 'SQLMESH__ORDER_STAGE__2493001244', 'SQLMESH__ORDER_PROFIT__417197957', 'SQLMESH__CUSTOMER_PROFIT__4259417223') (base.py:2113)
2025-03-11 17:17:09,584 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:17:10,117 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:17:10,479 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH' (evaluator.py:1061)
2025-03-11 17:17:10,480 - MainThread - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:10,480 - MainThread - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:10,481 - MainThread - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:11,258 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE SCHEMA IF NOT EXISTS "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH" (base.py:2113)
2025-03-11 17:17:11,712 - ThreadPoolExecutor-16_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:11,712 - ThreadPoolExecutor-16_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:11,712 - ThreadPoolExecutor-16_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:12,695 - ThreadPoolExecutor-16_0 - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__CUSTOMER_STAGE__3527124355' (evaluator.py:1403)
2025-03-11 17:17:12,697 - ThreadPoolExecutor-16_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE TABLE IF NOT EXISTS "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" AS SELECT "CUSTOMERID" AS "CUSTOMERID", "CUSTOMERNAME" AS "CUSTOMERNAME", "SEGMENT" AS "SEGMENT", "COUNTRY" AS "COUNTRY" FROM "DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMERS_T" AS "CUSTOMERS_T" WHERE FALSE LIMIT 0 (base.py:2113)
2025-03-11 17:17:13,233 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:13,945 - ThreadPoolExecutor-16_1 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:13,946 - ThreadPoolExecutor-16_1 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:13,946 - ThreadPoolExecutor-16_1 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:15,065 - ThreadPoolExecutor-16_1 - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__ORDER_PROFIT__417197957' (evaluator.py:1403)
2025-03-11 17:17:15,067 - ThreadPoolExecutor-16_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE TABLE IF NOT EXISTS "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS SELECT "O"."ORDERID" AS "ORDERID", "O"."ORDERDATE" AS "ORDERDATE", "O"."CUSTOMERID" AS "CUSTOMERID", "O"."PRODUCTID" AS "PRODUCTID", "O"."SHIPDATE" AS "SHIPDATE", "O"."SHIPMODE" AS "SHIPMODE", "O"."ORDERCOSTPRICE" AS "ORDERCOSTPRICE", "O"."ORDERSELLINGPRICE" AS "ORDERSELLINGPRICE", "O"."ORDERSELLINGPRICE" - "O"."ORDERCOSTPRICE" AS "ORDERPROFIT", "C"."CUSTOMERNAME" AS "CUSTOMERNAME", "C"."SEGMENT" AS "SEGMENT", "C"."COUNTRY" AS "COUNTRY", "P"."CATEGORY" AS "CATEGORY", "P"."PRODUCTNAME" AS "PRODUCTNAME", "P"."SUBCATEGORY" AS "SUBCATEGORY" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_STAGE__2493001244" AS "O" JOIN "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" AS "C" ON "C"."CUSTOMERID" = "O"."CUSTOMERID" JOIN "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_STAGE__8161499" AS "P" ON "O"."PRODUCTID" = "P"."PRODUCTID" WHERE FALSE LIMIT 0 (base.py:2113)
2025-03-11 17:17:16,518 - ThreadPoolExecutor-16_0 - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__CUSTOMER_PROFIT__4259417223' (evaluator.py:1403)
2025-03-11 17:17:16,585 - ThreadPoolExecutor-16_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE TABLE IF NOT EXISTS "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_PROFIT__4259417223" AS SELECT "ORDER_PROFIT"."CUSTOMERID" AS "CUSTOMERID", "ORDER_PROFIT"."SEGMENT" AS "SEGMENT", "ORDER_PROFIT"."COUNTRY" AS "COUNTRY", SUM("ORDER_PROFIT"."ORDERPROFIT") AS "PROFIT" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS "ORDER_PROFIT" WHERE FALSE GROUP BY "ORDER_PROFIT"."CUSTOMERID", "ORDER_PROFIT"."SEGMENT", "ORDER_PROFIT"."COUNTRY" LIMIT 0 (base.py:2113)
2025-03-11 17:17:16,586 - ThreadPoolExecutor-16_2 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:16,586 - ThreadPoolExecutor-16_2 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:16,586 - ThreadPoolExecutor-16_2 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:17,521 - ThreadPoolExecutor-16_2 - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__PRODUCT_PROFIT__136943708' (evaluator.py:1403)
2025-03-11 17:17:17,522 - ThreadPoolExecutor-16_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE TABLE IF NOT EXISTS "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_PROFIT__136943708" AS SELECT "ORDER_PROFIT"."PRODUCTID" AS "PRODUCTID", "ORDER_PROFIT"."PRODUCTNAME" AS "PRODUCTNAME", "ORDER_PROFIT"."CATEGORY" AS "CATEGORY", "ORDER_PROFIT"."SUBCATEGORY" AS "SUBCATEGORY", SUM("ORDER_PROFIT"."ORDERPROFIT") AS "PROFIT" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS "ORDER_PROFIT" WHERE FALSE GROUP BY "ORDER_PROFIT"."PRODUCTID", "ORDER_PROFIT"."PRODUCTNAME", "ORDER_PROFIT"."CATEGORY", "ORDER_PROFIT"."SUBCATEGORY" LIMIT 0 (base.py:2113)
2025-03-11 17:17:18,416 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:18,736 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:17:18,924 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:17:19,140 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:17:19,313 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:17:19,559 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:17:19,813 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:17:23,695 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:28,838 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:29,361 - ThreadPoolExecutor-25_0 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_STAGE": 2772891127> (evaluator.py:595)
2025-03-11 17:17:29,362 - ThreadPoolExecutor-25_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:29,362 - ThreadPoolExecutor-25_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:29,362 - ThreadPoolExecutor-25_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:30,585 - ThreadPoolExecutor-25_0 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-02-03 00:00:00, 2025-03-11 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__CUSTOMER_STAGE__3527124355' (evaluator.py:649)
2025-03-11 17:17:30,585 - ThreadPoolExecutor-25_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" (base.py:2113)
2025-03-11 17:17:30,844 - ThreadPoolExecutor-25_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" AS SELECT CAST("CUSTOMERID" AS VARCHAR(16777216)) AS "CUSTOMERID", CAST("CUSTOMERNAME" AS VARCHAR(16777216)) AS "CUSTOMERNAME", CAST("SEGMENT" AS VARCHAR(16777216)) AS "SEGMENT", CAST("COUNTRY" AS VARCHAR(16777216)) AS "COUNTRY" FROM (SELECT "CUSTOMERID" AS "CUSTOMERID", "CUSTOMERNAME" AS "CUSTOMERNAME", "SEGMENT" AS "SEGMENT", "COUNTRY" AS "COUNTRY" FROM "DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMERS_T" AS "CUSTOMERS_T") AS "_subquery" (base.py:2113)
2025-03-11 17:17:32,734 - ThreadPoolExecutor-25_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:32,734 - ThreadPoolExecutor-25_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:32,734 - ThreadPoolExecutor-25_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:33,666 - ThreadPoolExecutor-25_0 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-02-03 00:00:00, 2025-03-11 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_STAGE": 2772891127> (facade.py:506)
2025-03-11 17:17:33,667 - ThreadPoolExecutor-25_0 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_STAGE": 2772891127> (interval.py:210)
2025-03-11 17:17:34,023 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:39,259 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:39,893 - ThreadPoolExecutor-25_1 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_PROFIT": 2121590543> (evaluator.py:595)
2025-03-11 17:17:39,894 - ThreadPoolExecutor-25_1 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:39,894 - ThreadPoolExecutor-25_1 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:39,894 - ThreadPoolExecutor-25_1 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:40,833 - ThreadPoolExecutor-25_1 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-02-03 00:00:00, 2025-03-11 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__ORDER_PROFIT__417197957' (evaluator.py:649)
2025-03-11 17:17:40,833 - ThreadPoolExecutor-25_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" (base.py:2113)
2025-03-11 17:17:41,091 - ThreadPoolExecutor-25_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS SELECT CAST("ORDERID" AS DECIMAL(38, 0)) AS "ORDERID", CAST("ORDERDATE" AS VARCHAR(16777216)) AS "ORDERDATE", CAST("CUSTOMERID" AS VARCHAR(16777216)) AS "CUSTOMERID", CAST("PRODUCTID" AS VARCHAR(16777216)) AS "PRODUCTID", CAST("SHIPDATE" AS VARCHAR(16777216)) AS "SHIPDATE", CAST("SHIPMODE" AS VARCHAR(16777216)) AS "SHIPMODE", CAST("ORDERCOSTPRICE" AS DECIMAL(38, 0)) AS "ORDERCOSTPRICE", CAST("ORDERSELLINGPRICE" AS DECIMAL(38, 0)) AS "ORDERSELLINGPRICE", CAST("ORDERPROFIT" AS DECIMAL(38, 0)) AS "ORDERPROFIT", CAST("CUSTOMERNAME" AS VARCHAR(16777216)) AS "CUSTOMERNAME", CAST("SEGMENT" AS VARCHAR(16777216)) AS "SEGMENT", CAST("COUNTRY" AS VARCHAR(16777216)) AS "COUNTRY", CAST("CATEGORY" AS VARCHAR(16777216)) AS "CATEGORY", CAST("PRODUCTNAME" AS VARCHAR(16777216)) AS "PRODUCTNAME", CAST("SUBCATEGORY" AS VARCHAR(16777216)) AS "SUBCATEGORY" FROM (SELECT "O"."ORDERID" AS "ORDERID", "O"."ORDERDATE" AS "ORDERDATE", "O"."CUSTOMERID" AS "CUSTOMERID", "O"."PRODUCTID" AS "PRODUCTID", "O"."SHIPDATE" AS "SHIPDATE", "O"."SHIPMODE" AS "SHIPMODE", "O"."ORDERCOSTPRICE" AS "ORDERCOSTPRICE", "O"."ORDERSELLINGPRICE" AS "ORDERSELLINGPRICE", "O"."ORDERSELLINGPRICE" - "O"."ORDERCOSTPRICE" AS "ORDERPROFIT", "C"."CUSTOMERNAME" AS "CUSTOMERNAME", "C"."SEGMENT" AS "SEGMENT", "C"."COUNTRY" AS "COUNTRY", "P"."CATEGORY" AS "CATEGORY", "P"."PRODUCTNAME" AS "PRODUCTNAME", "P"."SUBCATEGORY" AS "SUBCATEGORY" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_STAGE__2493001244" AS "O" JOIN "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" AS "C" ON "C"."CUSTOMERID" = "O"."CUSTOMERID" JOIN "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_STAGE__8161499" AS "P" ON "O"."PRODUCTID" = "P"."PRODUCTID") AS "_subquery" (base.py:2113)
2025-03-11 17:17:42,619 - ThreadPoolExecutor-25_1 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:42,620 - ThreadPoolExecutor-25_1 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:42,620 - ThreadPoolExecutor-25_1 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:43,683 - ThreadPoolExecutor-25_1 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-02-03 00:00:00, 2025-03-11 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_PROFIT": 2121590543> (facade.py:506)
2025-03-11 17:17:43,683 - ThreadPoolExecutor-25_1 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."ORDER_PROFIT": 2121590543> (interval.py:210)
2025-03-11 17:17:44,588 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:49,951 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:50,447 - ThreadPoolExecutor-25_0 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_PROFIT": 2716878988> (evaluator.py:595)
2025-03-11 17:17:50,448 - ThreadPoolExecutor-25_2 - sqlmesh.core.snapshot.evaluator - INFO - Evaluating snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_PROFIT": 1238932029> (evaluator.py:595)
2025-03-11 17:17:50,457 - ThreadPoolExecutor-25_0 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-02-03 00:00:00, 2025-03-11 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__CUSTOMER_PROFIT__4259417223' (evaluator.py:649)
2025-03-11 17:17:50,458 - ThreadPoolExecutor-25_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_PROFIT__4259417223" (base.py:2113)
2025-03-11 17:17:50,458 - ThreadPoolExecutor-25_2 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:50,458 - ThreadPoolExecutor-25_2 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:50,458 - ThreadPoolExecutor-25_2 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:52,371 - ThreadPoolExecutor-25_2 - sqlmesh.core.snapshot.evaluator - INFO - Inserting batch (2025-02-03 00:00:00, 2025-03-11 00:00:00) into DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__PRODUCT_PROFIT__136943708' (evaluator.py:649)
2025-03-11 17:17:52,371 - ThreadPoolExecutor-25_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_PROFIT__136943708" (base.py:2113)
2025-03-11 17:17:52,659 - ThreadPoolExecutor-25_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_PROFIT__136943708" AS SELECT CAST("PRODUCTID" AS VARCHAR(16777216)) AS "PRODUCTID", CAST("PRODUCTNAME" AS VARCHAR(16777216)) AS "PRODUCTNAME", CAST("CATEGORY" AS VARCHAR(16777216)) AS "CATEGORY", CAST("SUBCATEGORY" AS VARCHAR(16777216)) AS "SUBCATEGORY", CAST("PROFIT" AS DECIMAL(38, 0)) AS "PROFIT" FROM (SELECT "ORDER_PROFIT"."PRODUCTID" AS "PRODUCTID", "ORDER_PROFIT"."PRODUCTNAME" AS "PRODUCTNAME", "ORDER_PROFIT"."CATEGORY" AS "CATEGORY", "ORDER_PROFIT"."SUBCATEGORY" AS "SUBCATEGORY", SUM("ORDER_PROFIT"."ORDERPROFIT") AS "PROFIT" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS "ORDER_PROFIT" GROUP BY "ORDER_PROFIT"."PRODUCTID", "ORDER_PROFIT"."PRODUCTNAME", "ORDER_PROFIT"."CATEGORY", "ORDER_PROFIT"."SUBCATEGORY") AS "_subquery" (base.py:2113)
2025-03-11 17:17:52,670 - ThreadPoolExecutor-25_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE TABLE "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_PROFIT__4259417223" AS SELECT CAST("CUSTOMERID" AS VARCHAR(16777216)) AS "CUSTOMERID", CAST("SEGMENT" AS VARCHAR(16777216)) AS "SEGMENT", CAST("COUNTRY" AS VARCHAR(16777216)) AS "COUNTRY", CAST("PROFIT" AS DECIMAL(38, 0)) AS "PROFIT" FROM (SELECT "ORDER_PROFIT"."CUSTOMERID" AS "CUSTOMERID", "ORDER_PROFIT"."SEGMENT" AS "SEGMENT", "ORDER_PROFIT"."COUNTRY" AS "COUNTRY", SUM("ORDER_PROFIT"."ORDERPROFIT") AS "PROFIT" FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" AS "ORDER_PROFIT" GROUP BY "ORDER_PROFIT"."CUSTOMERID", "ORDER_PROFIT"."SEGMENT", "ORDER_PROFIT"."COUNTRY") AS "_subquery" (base.py:2113)
2025-03-11 17:17:53,912 - ThreadPoolExecutor-25_0 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-02-03 00:00:00, 2025-03-11 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_PROFIT": 2716878988> (facade.py:506)
2025-03-11 17:17:53,913 - ThreadPoolExecutor-25_0 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."CUSTOMER_PROFIT": 2716878988> (interval.py:210)
2025-03-11 17:17:53,935 - ThreadPoolExecutor-25_2 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:17:53,936 - ThreadPoolExecutor-25_2 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:17:53,936 - ThreadPoolExecutor-25_2 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:17:55,095 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:17:55,182 - ThreadPoolExecutor-25_2 - sqlmesh.core.state_sync.db.facade - INFO - Adding interval (2025-02-03 00:00:00, 2025-03-11 00:00:00) for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_PROFIT": 1238932029> (facade.py:506)
2025-03-11 17:17:55,183 - ThreadPoolExecutor-25_2 - sqlmesh.core.state_sync.db.interval - INFO - Pushing intervals for snapshot SnapshotId<"DB_ADI_SQLMESH_DEV"."SQLMESH"."PRODUCT_PROFIT": 1238932029> (interval.py:210)
2025-03-11 17:18:00,284 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:18:02,592 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:02,800 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:02,986 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:03,195 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:03,372 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:03,560 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:03,737 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:03,972 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:04,414 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:04,880 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:05,264 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:05,510 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:05,656 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:18:05,720 - MainThread - sqlmesh.core.state_sync.db.facade - INFO - Promoting environment 'dev' (facade.py:165)
2025-03-11 17:18:10,795 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:18:14,863 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'DB_ADI_SQLMESH_DEV.SQLMESH__DEV' (evaluator.py:1061)
2025-03-11 17:18:14,865 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE SCHEMA IF NOT EXISTS "DB_ADI_SQLMESH_DEV"."SQLMESH__DEV" (base.py:2113)
2025-03-11 17:18:15,417 - ThreadPoolExecutor-57_0 - sqlmesh.core.snapshot.evaluator - INFO - Updating view 'DB_ADI_SQLMESH_DEV.SQLMESH__DEV.CUSTOMER_STAGE' to point at table 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__CUSTOMER_STAGE__3527124355' (evaluator.py:1368)
2025-03-11 17:18:15,419 - ThreadPoolExecutor-57_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:18:15,419 - ThreadPoolExecutor-57_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:18:15,419 - ThreadPoolExecutor-57_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:18:16,346 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:18:16,961 - ThreadPoolExecutor-57_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE VIEW "DB_ADI_SQLMESH_DEV"."SQLMESH__DEV"."CUSTOMER_STAGE" COPY GRANTS AS SELECT * FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_STAGE__3527124355" (base.py:2113)
2025-03-11 17:18:18,727 - ThreadPoolExecutor-57_1 - sqlmesh.core.snapshot.evaluator - INFO - Updating view 'DB_ADI_SQLMESH_DEV.SQLMESH__DEV.ORDER_PROFIT' to point at table 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__ORDER_PROFIT__417197957' (evaluator.py:1368)
2025-03-11 17:18:18,728 - ThreadPoolExecutor-57_1 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:18:18,729 - ThreadPoolExecutor-57_1 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:18:18,729 - ThreadPoolExecutor-57_1 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:18:19,626 - ThreadPoolExecutor-57_1 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE VIEW "DB_ADI_SQLMESH_DEV"."SQLMESH__DEV"."ORDER_PROFIT" COPY GRANTS AS SELECT * FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__ORDER_PROFIT__417197957" (base.py:2113)
2025-03-11 17:18:20,997 - ThreadPoolExecutor-57_0 - sqlmesh.core.snapshot.evaluator - INFO - Updating view 'DB_ADI_SQLMESH_DEV.SQLMESH__DEV.CUSTOMER_PROFIT' to point at table 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__CUSTOMER_PROFIT__4259417223' (evaluator.py:1368)
2025-03-11 17:18:20,998 - ThreadPoolExecutor-57_2 - sqlmesh.core.snapshot.evaluator - INFO - Updating view 'DB_ADI_SQLMESH_DEV.SQLMESH__DEV.PRODUCT_PROFIT' to point at table 'DB_ADI_SQLMESH_DEV.sqlmesh__SQLMESH.SQLMESH__PRODUCT_PROFIT__136943708' (evaluator.py:1368)
2025-03-11 17:18:21,001 - ThreadPoolExecutor-57_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE VIEW "DB_ADI_SQLMESH_DEV"."SQLMESH__DEV"."CUSTOMER_PROFIT" COPY GRANTS AS SELECT * FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__CUSTOMER_PROFIT__4259417223" (base.py:2113)
2025-03-11 17:18:21,003 - ThreadPoolExecutor-57_2 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.11.9, Platform: Windows-10-10.0.22621-SP0 (connection.py:423)
2025-03-11 17:18:21,003 - ThreadPoolExecutor-57_2 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1226)
2025-03-11 17:18:21,003 - ThreadPoolExecutor-57_2 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1315)
2025-03-11 17:18:21,648 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:18:21,948 - ThreadPoolExecutor-57_2 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE VIEW "DB_ADI_SQLMESH_DEV"."SQLMESH__DEV"."PRODUCT_PROFIT" COPY GRANTS AS SELECT * FROM "DB_ADI_SQLMESH_DEV"."sqlmesh__SQLMESH"."SQLMESH__PRODUCT_PROFIT__136943708" (base.py:2113)
2025-03-11 17:18:23,161 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:23,380 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:23,636 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:23,811 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:24,059 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:24,292 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:24,520 - MainThread - sqlmesh.core.state_sync.db.environment - INFO - Finalizing environment 'dev' (environment.py:135)
2025-03-11 17:18:29,360 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:29,845 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:29,930 - event-emitter - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
2025-03-11 17:18:30,312 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:810)
2025-03-11 17:18:30,481 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:816)
2025-03-11 17:18:30,725 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
2025-03-11 17:18:31,046 - MainThread - sqlmesh.core.analytics.dispatcher - INFO - Failed to emit events: HTTPSConnectionPool(host='analytics.tobikodata.com', port=443): Max retries exceeded with url: /v1/sqlmesh/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) (dispatcher.py:138)
